language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction

script:
  - phpunit

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache