language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

script:
  - phpunit

notifications:
  email: false